# Generated by Django 4.0.1 on 2022-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('earliest_arrive_date', models.DateTimeField()),
                ('latest_arrive_date', models.DateTimeField()),
                ('special_request', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CONFIRMED', 'CONFIRMED'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=100)),
            ],
        ),
    ]
