# Generated by Django 4.0.1 on 2022-01-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='who_on_car',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
