# Generated by Django 4.0.1 on 2022-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
