# Generated by Django 4.0.1 on 2022-01-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='earliest_arrive_date',
            new_name='arrive_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='latest_arrive_date',
        ),
    ]
