# Generated by Django 4.0.1 on 2022-01-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
    ]
