# Generated by Django 4.0.1 on 2022-01-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_alter_ride_sharer_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='sharer_number',
            new_name='passenger_number',
        ),
    ]
