# Generated by Django 4.0.1 on 2022-01-30 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_alter_ride_passenger_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passenger_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
