# Generated by Django 4.0.1 on 2022-01-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_ride_seat_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='seat_available',
        ),
    ]
