# Generated by Django 4.0.1 on 2022-01-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0015_remove_ride_seat_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seat_available',
            field=models.IntegerField(default=0),
        ),
    ]
