# Generated by Django 4.0.1 on 2022-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('X', 'X(3 passengers)'), ('XL', 'XL(5 passengers)')], default='', max_length=20),
        ),
    ]
